cluster: a100-1  # fse-2a100-1.ai.rug.nl

paths:
  base_dir: /home/s5549329/math-llm-infrastructure
  data_dir: /scratch/s5549329/data/processed/openmathinstruct2
  output_dir: /scratch/s5549329/outputs/lora_8b
  hf_cache: /scratch/s5549329/.cache/huggingface

gpus:
  cuda_devices: "MIG-869856b9-7f12-5c12-a212-64c74ac0a85e,MIG-ec73ed57-6aa0-541d-9909-e4f6518cbd33"
  n_gpus: 2
